name: Render Jupyter Notebooks

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: dotnet tool install --global Microsoft.dotnet-interactive
    - run: dotnet interactive jupyter install
    - shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install pandoc
        sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic
    - shell: bash
      run: |
        jupyter nbconvert --to pdf --allow-chromium-download test.ipynb

